import { Inter } from "next/font/google";
import "./globals.css";
import { Oswald } from 'next/font/google';

const oswald = Oswald({
  weight: ['400', '700'],
  subsets: ['latin']
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={oswald.className}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
